import { Github, Linkedin, Mail } from "lucide-react";

export const PROJECTS = [
    {
        title: "Password Strength Checker",
        description:
            "An interactive security tool that provides real-time password validation with visual feedback. Features regex patterns, strength scoring, and security recommendations to demonstrate frontend security practices.",
        tags: ["Security", "React", "TypeScript", "Form Validation", "UX/UI"],
        image:
            "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=600&h=400&fit=crop&crop=center",
        link: "#tools-demo",
        aiHint: "cybersecurity lock shield",
    },
    {
        title: "QuickRead News Summarizer",
        description:
            "A web application that summarizes news articles from various sources, providing users with quick and concise information. Leverages NLP techniques for effective text summarization.",
        tags: ["NLP", "Text Summarization", "Web App", "Python"],
        image:
            "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&h=400&fit=crop&crop=center",
        link: "https://github.com/kanakmegha/QuickRead",
        aiHint: "news article concept",
    },
    {
        title: "AI-Generated Image Detection",
        description:
            "A deep learning model that detects whether an image is generated by AI. This project showcases skills in computer vision and building robust classification models.",
        tags: ["Deep Learning", "Computer Vision", "TensorFlow", "AI"],
        image:
            "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop&crop=center",
        link: "https://github.com/kanakmegha/AI-Generated-Image-Detection",
        aiHint: "AI image detection",
    },
    {
        title: "Disease Prediction System",
        description:
            "A machine learning model that predicts potential diseases based on user-inputted symptoms. Demonstrates practical application of ML in the healthcare domain.",
        tags: ["Machine Learning", "Scikit-learn", "Python", "Healthcare"],
        image:
            "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&h=400&fit=crop&crop=center",
        link: "https://github.com/kanakmegha/Disease-Prediction",
        aiHint: "medical data",
    },
    {
        title: "House Price Predictor",
        description:
            "Built a regression model to predict house prices based on various features like location, size, and amenities. This project involves data cleaning, feature engineering, and model evaluation.",
        tags: ["Machine Learning", "Regression", "Data Science", "Python"],
        image:
            "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&h=400&fit=crop&crop=center",
        link: "https://github.com/kanakmegha/HousePricePredictor",
        aiHint: "modern house architecture",
    },
    {
        title: "Budget Manager",
        description:
            "A tool to help users manage their finances by tracking income and expenses. A practical application of software development for personal finance.",
        tags: ["Finance", "Personal Tool", "Python"],
        image:
            "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=400&fit=crop&crop=center",
        link: "https://github.com/kanakmegha/BudgetManager",
        aiHint: "finance chart",
    },
    {
        title: "CPU Scheduling Simulator",
        description:
            "A visual lab simulator for demonstrating various CPU scheduling algorithms. An excellent project for understanding core computer science concepts.",
        tags: ["Computer Science", "Algorithms", "Simulation", "Java"],
        image:
            "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=600&h=400&fit=crop&crop=center",
        link: "https://github.com/kanakmegha/CPU-Scheduling-Simulator-VLAB",
        aiHint: "abstract computer processor",
    },
];
/*{
        company: "Unikul Solutions Pvt Ltd.",
        role: "Software Developer",
        date: "Aug 2024 - Present",
        description: " Assisted in developing and testing web-based modules using Python and RESTful APIs.\
        Contributed to backend–database integration for analytics dashboards and data reporting.\
        Built and optimized API endpoints for smooth data retrieval and transformation.\
        Participated in debugging, version control (Git), and deployment automation\
        (CI/CD pipelines). Collaborated with cross-functional teams to enhance system performance and scalability.\
        Automations: Designed and implemented Python scripts to automate repetitive manual tasks, improving efficiency and reducing errors. Leadership & Mentorship: Mentored a junior colleague to help them learn and grow in technical tasks. Managed a team, coordinated efforts, and ensured projects were delivered on time and within deadlines."
    },*/
export const EXPERIENCE = [
    {
        company: "Nexus Info",
        role: "AI/ML Intern",
        date: "Jun 2024 - Jul 2024",
        description:
            "Performed data cleaning, feature engineering, and model training using Python and Scikit-learn. Developed chatbots using Python and Flask, leveraging data from Ollama API or JSON files to handle user inputs and generate dynamic responses. Integrated APIs for real-time data retrieval and utilized JSON files for structured data storage, ensuring seamless interaction and accurate response generation. Integrated external APIs to fetch real-time data for analysis, ensuring seamless data flow and accuracy. Conducted exploratory data analysis (EDA) to identify trends and inform decision-making.",
    },
];

export const SOCIAL_LINKS = [
    {
        name: "LinkedIn",
        icon: Linkedin,
        href: "https://linkedin.com/in/kanakmegha",
    },
    { name: "GitHub", icon: Github, href: "https://github.com/skanakmegha/" },
    { name: "Email", icon: Mail, href: "mailto:kanakmegha@gmail.com" },
];

export const CERTIFICATIONS = [
    {
        title: "Introdction to Agent skills",
        issuer: "Anthropic",
        date: "2026",
        verificationUrl: "https://verify.skilljar.com/c/htefbz6srz7m",
        category: "AI/ML",
        logo:
            "https://images.unsplash.com/photo-1599305090740-983636904192?w=200&h=200&auto=format&fit=crop",
    },
    {
        title: "Advance Topics of MCP",
        issuer: "Anthropic",
        date: "2026",
        verificationUrl: "https://verify.skilljar.com/c/7xm5h5y7bwiu",
        category: "AI/ML",
        logo:
            "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=200&h=200&auto=format&fit=crop",
    },
    {
        title: "Fundamentals of Agents",
        issuer: "Hugging Face",
        date: "2026",
        verificationUrl:
            "https://cas-bridge.xethub.hf.co/xet-bridge-us/67a47037749ea2c4b9fafd4b/d17d5e6b9270196d55cd014d489e3995bfb2204a2bbf6a794401623b663a92d8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cas%2F20260319%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260319T104322Z&X-Amz-Expires=3600&X-Amz-Signature=180ae8490b44a4acf37efacae860c698a7e338f5e1c1563d073cdcfa83986f16&X-Amz-SignedHeaders=host&X-Xet-Cas-Uid=679272971f5a20f6cda6478f&response-content-disposition=inline%3B+filename*%3DUTF-8%27%272026-03-15.png%3B+filename%3D%222026-03-15.png%22%3B&response-content-type=image%2Fpng&x-amz-checksum-mode=ENABLED&x-id=GetObject&Expires=1773920602&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc3MzkyMDYwMn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2FzLWJyaWRnZS54ZXRodWIuaGYuY28veGV0LWJyaWRnZS11cy82N2E0NzAzNzc0OWVhMmM0YjlmYWZkNGIvZDE3ZDVlNmI5MjcwMTk2ZDU1Y2QwMTRkNDg5ZTM5OTViZmIyMjA0YTJiYmY2YTc5NDQwMTYyM2I2NjNhOTJkOCoifV19&Signature=e9eslBNGvf8ZvoqTr5ejk6va5TfF4P2sh8N3ahXpgQ8OoXIdzXds-lAKcIBd9KS6pmIGbdQByZnOs2-CjoDdzOl%7E5JJuvu3Jhgm0%7EyccAPVtW9yMtiylC3m9RwdZJNYuN8r-YCvBvIST-bFCnNYErdM%7EdhwsDOitw36KuZ1srmim-hOhUtGFGR3M5QAJt8LJqzl3afSn%7EDpnITkBpwqc-W78XTEAQwaS1Q3Hc75MF74tMZY-9A3WUjpaP71RHMrYR0y7ItvxnvncGfBA5I-N8hIMVCWT7TKeCuADC7sDqOtwmtFwJLI5PotcH3-y8NWDsUUiRKO6Gkebve0l1YO5Tw__&Key-Pair-Id=K2L8F4GPSG1IFC",
        category: "AI/ML",
        logo:
            "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=200&h=200&auto=format&fit=crop",
    },
    {
        title: "Fundamentals of Digital Marketing",
        issuer: "Google",
        date: "2026",
        verificationUrl:
            "https://skillshop.exceedlms.com/student/award/vo6KdMaHaAdkp8XMudZ55n3G",
        category: "Digital Marketing",
        logo:
            "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=200&h=200&auto=format&fit=crop",
    },
];
